spring:
  datasource:
    url: jdbc:mysql://localhost:3306/cryptocolleaguesdb
    username: ironhacker
    password: 1r0nh4ck3r
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update

cryptocolleagues:
  app:
    jwtCookieName: cryptocolleagues
    jwtSecret: cryptoKey
    jwtExpirationMs: 86400000